--// SELECT basics

--//SELECT THE POPULATION FROM GERMANY
SELECT population FROM world
  WHERE name = 'Germay'

--//SELECT THE POPULATION IN 3 DIFFERENT COUNTRIES
SELECT name, population FROM world
  WHERE name IN ('Sweden', 'Norway', 'India');

--//SELECT THE NAME AND AREA FROM THE WORLD WHERE THE AREA IS BETWEEN 200000 AND 250000
SELECT name, area FROM world
  WHERE area BETWEEN 200000 AND 250000

